### ISSUE TITLE
Doesn't work with latest shodown version

### ISSUE THREAD

**Issue by CyborTronik** [cybercase/showdown-target-blank#3]
Just installed latest version of showdown (1.1.0) and imported this extension.
Showdown can't find extension details.

**Comment by cybercase** [comment]
Hello @CyborTronik 
Could you provide a simple test case? So I can reproduce the issue and try to fix it.

Thanks

**Comment by elebetsamer** [comment]
If you installed via bower like I did, that is likely the problem. The current release 0.0.2 (a2acb4107ef10370919b5204fb8356ee959f06e4) has a problem with the dist files, because showdown is capitalized. If a new release tag is added to the repo, that should resolve this problem.

**Comment by cybercase** [comment]
Thanks @elebetsamer ... I'm mostly an `npm` user and I completely forgot to tag the new version for bower.
Fixed.

**Comment by elebetsamer** [comment]
Yep, that fixed it for me using Bower. Thanks.
