### ISSUE TITLE
Use lazy quantifier for the reg ex

### ISSUE THREAD

**Issue by elebetsamer** [cybercase/showdown-target-blank#4]
The regular expression as it is now, `<a(.*)a>`, captures too many characters. I suggest changing it to `<a(.*?)>` so that it is less greedy.

Here is an example where it captures both links at the same time:
![image](https://cloud.githubusercontent.com/assets/75610/10877426/f14e4388-80fa-11e5-91d1-b7be39c99497.png)

Here it is with the lazy quantifier added to the reg ex:
![image](https://cloud.githubusercontent.com/assets/75610/10877460/3aa8032a-80fb-11e5-9c9b-1e2a3ef6ec3b.png)

Of course, since we left off the trailing `a` in the reg ex as well, you'd also have to change the return as well from `return '<a target="_blank"' + content + 'a>';` to `return '<a target="_blank"' + content + '>';`

If you'd like, I can submit a PR for this.

**Comment by elebetsamer** [comment]
Hmm, just tested this locally and it only places the _blank on the first link in the text block. Do you know if it is possible to get showdown to process multiple matches?

**Comment by cybercase** [comment]
Just merged #5 
@elebetsamer Many thanks for spotting and fixing this issue.
