### ISSUE TITLE
grunt required for post install script

### ISSUE THREAD

**Issue by p-m-p** [cybercase/showdown-target-blank#6]
Hi,

just wanted to use your package but am not able to install due to your post installation requiring grunt.

**Comment by cybercase** [comment]
Hi @p-m-p,
thanks for pointing out this issue. Grunt is a dev dependency and you should not be forced to install Grunt just to use this package.

I removed grunt from postinstall scripts and updated the npm package. Let me know if everything works fine.

**Comment by p-m-p** [comment]
Nice one. Thanks for the quick response!
